### ISSUE TITLE
Don't rest on REST (Swagger)

### ISSUE THREAD

**Issue by niklas-heer** [dev-night/talks#10]
* **Speaker**:  Fabian (@Akuryou) & Niklas (@niklas-heer) 
* **Duration**: 15m (Introduction to REST) + 30m (Swagger)
* **Slides**: http://akuryou.github.io/introduction-to-swagger/ (some)
* **Description**: Frist we dive into what REST is and talk about some best practices. Than it'll be all about [Swagger](http://swagger.io/). We will show you how the tool works and why it is pretty cool. 

(ref: #12)

**Comment by stesie** [comment]
... GraphQL would also make for a nice session, wouldn't it?

**Comment by niklas-heer** [comment]
@stesie true. Should it be a separate session or should the speaker decide what he/she wants to talk about?

**Comment by stesie** [comment]
@niklas-heer I think both are large enough topics, and distinct fields. So even if one speaker wants to do both, merely session time suggests to split it both up.

And also to have the "hands on" part focussed

**Comment by niklas-heer** [comment]
@stesie good point. I'll create a second issue.

**Comment by Akuryou** [comment]
Got a talk about swagger and useful related libraries.
But it does not cover REST basics and best practices.

http://akuryou.github.io/introduction-to-swagger/

**Comment by niklas-heer** [comment]
@Akuryou That's very cool. We could do a collaboration and I could briefly cover the basics and some [best practices](https://zalando.github.io/restful-api-guidelines/). After that you could dive deeper into Swagger. What do you think?

**Comment by Akuryou** [comment]
Actually there is often a lot of confusion about what REST really is.
Most people think REST == "Some API I call via HTTP". Which is very far from the truth.

Therefore I think an additional talk about what REST really is might be good.

**Comment by niklas-heer** [comment]
Awesome so I would change the issue accordingly and then it's open for votes. Okay?

**Comment by niklas-heer** [comment]
I've updated the main issue.  :smiley:

**Comment by proudcommerce** [comment]
a pity ... sitting at the airplane in this time :-(

**Comment by niklas-heer** [comment]
@proudcommerce That's really unfortunate timing. But there is an issue for GraphQL. So it won't be the last talk about APIs. :)

**Comment by niklas-heer** [comment]
Closing the talk. Here are the slides: https://github.com/dev-night/talks/tree/master/slides/2017/012_dont-rest-on-rest
