### ISSUE TITLE
Riding the whale (Docker)

### ISSUE THREAD

**Issue by niklas-heer** [dev-night/talks#13]
* **Speaker**: @jochenchrist 
* **Planned**: 2017-09-12
* **Slides**: https://github.com/dev-night/talks/tree/master/slides/2017/014_riding-the-whale
* **Description**: Short introduction into [Docker](https://www.docker.com/). Best practices. Why it's cool to use and how.

**Inhalt**:
* Was ist Docker und wie unterscheidet es sich von VMs?
* Wie erstelle ich Docker Images via Dockerfile
* Wie führe ich Docker Container lokal aus
* Wie baue ich mit Docker Compose eine Anwendung aus verschiedenen Docker Images zusammen

**Comment by jochenchrist** [comment]
Ich kann gerne anbieten, einen Talk zu Docker vorzubereiten.

Gerne auch als Live-"Coding" Session, in der eine heterogene Fullstack Webanwendung (z. B. EmberJS Frontend, Spring Boot Service, MongoDB) erstellt wird.

Inhalt:
Was ist Docker und wie unterscheidet es sich von VMs?
Wie erstelle ich Docker Images via Dockerfile
Wie führe ich Docker Container lokal aus
Wie baue ich mit Docker Compose eine Anwendung aus verschiedenen Docker Images zusammen

**Comment by niklas-heer** [comment]
@jochenchrist sehr cool! Ja sehr gerne. Wie wäre es mit der /dev/night im September, also 12.09?

(im August ist schon ne andere /dev/night geplant, mehr dazu morgen ^^)

**Comment by jochenchrist** [comment]
Ja, 12.09. sieht gut aus.

**Comment by niklas-heer** [comment]
Super! :) Dann lass uns das mal ins Auge fassen. Können ja morgen uns nochmal kurz unterhalten, wenn du da bist.

**Comment by niklas-heer** [comment]
Thanks to Jochen for the great talk! Here are the slides: https://github.com/dev-night/talks/tree/master/slides/2017/014_riding-the-whale
