### ISSUE TITLE
Taming the snake (Python)

### ISSUE THREAD

**Issue by niklas-heer** [dev-night/talks#14]
* **Speaker**: NEEDED
* **Description**: A talk which explains the basics of [Python](https://www.python.org/). What fancy black magic is possible with duck typing? What is it good for? What are it's principles? Limitations?

**Comment by niklas-heer** [comment]
@Akuryou would you like to give this talk?

**Comment by ThomasChr** [comment]
FYI: A general introduction to Python will be given here: https://github.com/dev-night/talks/issues/29

**Comment by niklas-heer** [comment]
True so we get 2 for one :laughing: 

So I'll close this one.
