### ISSUE TITLE
Serverless Backends

### ISSUE THREAD

**Issue by stesie** [dev-night/talks#19]
* **Speaker**: @stesie
* **Duration**: no idea
* **Slides**: n/a yet, just a proposal
* **Description**: What's *serverless*? Apart from being just another buzzword? I'd focus on serverless services provided by AWS. Give a brief overview over the services likely to be involved (Lambda, API Gateway, DynamoDB, S3, Cognito) + the "serverless framework" (serverless.com) which is a CLI tool to manage serverless services; and last but not least: how does all that influence the overall architecture

**Comment by niklas-heer** [comment]
Awesome I really like this topic. Since January is either filled with GGJ prep or the bitcoin talk. 
We could do that talk on the 13th February if that fits your schedule.

**Comment by stesie** [comment]
Well, unfortunately I can't definitely confirm that date. I probably will be on a new project from Jan 15 on and likely to be colocated with the customer for the first couple of weeks (that's also why I voted for Jan 9 yesterday). So let's either wait some days (should become clear during next couple of days) or go with March 8 instead.

**Comment by niklas-heer** [comment]
Ah sure thing. No pressure. :) 
We'll just see how it will turn out.

**Comment by niklas-heer** [comment]
Hey @stesie would you like to give your talk on our special event for the WueWW? 
But there would only be 30m available which might be a bit short for such a topic...

**Comment by stesie** [comment]
I'm likely to be in Remscheid by then and also 30m is too short. For slides and upcoming discussions I'd expect like 1h and then I think it's a nice topic to take a little challenge afterwards.

... so we should ask people to bring AWS accounts to play with in meetup.com invitation :)   so no time's lost when people try to sign up for those accounts ...

**Comment by niklas-heer** [comment]
Yes you're completely right this topic needs more time and trying it out is the best part. ^^
Maybe in April then? :)

**Comment by stesie** [comment]
should work out fine

**Comment by niklas-heer** [comment]
Awesome, thanks! :)

**Comment by niklas-heer** [comment]
Was a great talk! Thank you very much!
Here are the notes for the talk:
https://github.com/dev-night/talks/tree/master/slides/2018/021_serverless
