### ISSUE TITLE
Domain Driven Design

### ISSUE THREAD

**Issue by jochenchrist** [dev-night/talks#20]
* **Speaker**: NEEDED
* **Duration**: TBD
* **Slides**: e.g. https://speakerdeck.com/mploed/ddd-workshop-at-microxchg
* **Description**: DDD has a number of concepts and practices to create better software and more importantly enables IT and business to establish a mutual understanding.

**Comment by jochenchrist** [comment]
Ich kann gerne anbieten, einen Talk zu DDD zu halten (ab September).

Da das Thema sehr groß ist, würde ich es zunächst auf Strategic Design beschränken, und Tactical Design in einem separaten Talk.

**Comment by niklas-heer** [comment]
Oh sehr geil, September wäre auf jeden Fall noch frei. Können wir auch so ins Auge fassen. 

Wir machen auch wieder an der Nürnberger WebWeek mit - was am 16.10.2018 stattfinden wird - dafür suchen wir auch noch Speaker für nen 30-40 Minuten Vortrag. Falls du da Bock drauf hast :)

**Comment by jochenchrist** [comment]
Ja, dann lass uns doch mal den September festhalten.

**Comment by niklas-heer** [comment]
Also die /dev/night im September findet am 11. statt - passt bei dir noch? 
Du hälst den Talk auf Englisch oder?

**Comment by jochenchrist** [comment]
Passt.
Talk ist auf Deutsch.

**Comment by niklas-heer** [comment]
Top. Könntest du den Talk auch auf Englisch halten, da wir Interesse von englischsprachigen Entwicklern haben?

**Comment by jochenchrist** [comment]
Hallo Niklas,

das verstehe ich.
Bei DDD geht es um Kommunikation, um eine gemeinsame Sprache - mit den Domänenexperten, Fachexperten und Entwicklern.

Leider ist mein Englisch nicht gut genug, um das Meta-Thema DDD Strategisches Design souverän vorzustellen, daher würde ich den Talk wirklich lieber auf Deutsch halten.

**Comment by niklas-heer** [comment]
Alles klar, das verstehe ich vollkommen - ich habe nichts dagegen wenn mal ein Talk auf Deutsch ist, aber ich versuche eben das so gering wie möglich zu halten, damit eben auch möglichst viele was davon haben. 😃 

Aber mach dir kein Kopf, das geht klar! Nochmal vielen Dank dass du einen Vortrag halten willst. Weiß das sehr zu schätzen! 👍

**Comment by mjainta** [comment]
Hi Jochen, hier ist der Ordner für deine Slides.
Wäre klasse wenn du diese nach deinem Vortrag hinzufügen könntest :smiley: 
https://github.com/dev-night/talks/tree/master/slides/2018/026_ddd-strategic-design
