### ISSUE TITLE
Password-less Authentication

### ISSUE THREAD

**Issue by jochenchrist** [dev-night/talks#21]
* **Speaker**: Jochen Christ
* **Planned**: 2017-12-12 (no. 17)
* **Duration**: 45m
* **Description**: Passwords are insecure and inconvenient for many users. Every day hacked password databases are reported and studies show a a drop in conversion rate in e-commerce when a registration with password is mandatory. We will talk about alternatives that rely on biometrics, possession or One-Time Tokens with the advantages and disadvantages.

**Comment by niklas-heer** [comment]
Nice I really like this topic! Do you want to do it in December?

**Comment by jochenchrist** [comment]
When is December's dev-night?

**Comment by niklas-heer** [comment]
It will be on the 12th of December.

**Comment by jochenchrist** [comment]
Yepp, I can arrange that.

**Comment by niklas-heer** [comment]
Awesome! Do you want to do a practice after it?
Because I thought that may be a bit difficult, so I would look for a second smaller talk afterwards.

What do you think?

**Comment by jochenchrist** [comment]
I don't think there will be much practical stuff.

We could play around with some password cracking tools ;-)

**Comment by niklas-heer** [comment]
Ok :) We'll see if I can find a smaller talk. 
But thank you for your contribution! It's really great! :)

**Comment by jochenchrist** [comment]
I'll do some collaboration part, so I'd be happy to fill 90-120 minutes.

**Comment by niklas-heer** [comment]
Okay very cool :) Then I'll create the event. :)

**Comment by niklas-heer** [comment]
I've created [**the event**](https://www.meetup.com/de-DE/dev_night/events/245636494).

Here is the folder for your slides: https://github.com/dev-night/talks/tree/master/slides/2017/017_no-password-no-cry

**Comment by niklas-heer** [comment]
@jochenchrist Thank you very much for the really cool talk yesterday! I think I have to try magic links now :laughing: 

I think these are your slides: http://slides.com/jochenchrist/passwordfree#/ 
Is this correct?

**Comment by jochenchrist** [comment]
Take these: https://slides.com/jochenchrist/passwordfree-devnight/

**Comment by niklas-heer** [comment]
Awesome, thank you! :+1:
