### ISSUE TITLE
Kubernetes Deep Dive

### ISSUE THREAD

**Issue by hakoerber** [dev-night/talks#22]
* **Speaker**: Hannes Körber (hannes.koerber@gmail.com)
* **Duration**: TBD
* **Slides**: TBD
* **Description**: I will give an introduction to [Kubernetes](https://kubernetes.io/), the container orchestrator by Google!

Subtopics:

* What is Kubernetes? What do you use it for?
* What are the main concepts behind Kubernetes?
* How does it fit into the DevOps world?
* How can you make a project "Kubernetes-ready"?

Maybe we can do some hands-on demonstration, too.

**Comment by niklas-heer** [comment]
Awesome. Thank you very much. That talk would be great so would you like to do it on the next /dev/night (08.05)?

**Comment by hakoerber** [comment]
Yep, I'm in!

I will prepare a rough plan/overview and then we can talk about specifics.

**Comment by niklas-heer** [comment]
Perfect! Looking forward to it :smiley:
