### ISSUE TITLE
Kafka & Kafka Streams

### ISSUE THREAD

**Issue by stesie** [dev-night/talks#25]
* **Speaker**: @stesie
* **Duration**:1h
* **Slides**: noch nicht erstellt, nur mal ein Vorschlag ...
* **Description**: 

Kafka ist eine Event Streaming Plattform bzw. ein Message Broker.  Ich könnte/würde die Konzepte hinter Kafka vorstellen, bzw. grob eine Abgrenzung zu den "üblicheren" AMQP-basierten Message Brokern (a la RabbitMQ) ziehen.  Also was sind Topics, Partitionen, Message Rentention, welche Patterns gibt es bzgl. Consumer Groups.  RabbitMQ etc. an sich würde ich jedoch out-of-scope sehen

Als zweiten Part würde ich kafka-streams zeigen wollen, eine Stream Processing (Client) Library, die auf Kafka aufsetzt und mit der man in einer Art DSL dann funktional formulierte Datenverarbeitungs-Pipelines zusammenstellen kann.

... dazu halt Codebeispiele aus der Java/Spring Boot Ecke

**Comment by niklas-heer** [comment]
Wow sehr cooler Vorschlag :+1:, danke :)

Hast du eine Präferenz wann du den talk halten möchtest?

**Comment by stesie** [comment]
nö, keine Terminpräferenz. Slides sind noch nicht ganz fertig, habe aber schon einen guten Teil, kann also auch "bald" sein, as in 10.07. wäre ok für mich, gerne aber auch später.

**Comment by niklas-heer** [comment]
Ah top, dann lass uns nach der /dev/night am Dienstag schauen, weil beim letzten mal wollte noch jemand eine Talk im Juli halten. :)  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by stesie** [comment]
Joar, geht klar. Mein Herz hängt auch nicht am Juli, wollte eher sagen "geht auch zeitnah".  August (oder ggf. später) ist für mich auch fein.  Klären wir morgen.
