### ISSUE TITLE
Micropython

### ISSUE THREAD

**Issue by ThomasChr** [dev-night/talks#29]
* **Speaker**: Thomas Christlieb (thomaschristlieb@hotmail.com)
* **Duration**: 30m Theory, Open End Practice
* **Slides**: 
* **Description**: `First a quick overview over Micropython. Something like what is it and how you can control the real world with it easily. After that we're going to have some practice with a few cheap Boards and a little bit of Hardware I'll bring along.`

**Comment by niklas-heer** [comment]
Wow amazing idea! I would love if we could to some hardware stuff!
Thank you very much for your talk submission. :+1: 

Regarding the schedule, we already have an event planned for September and October.
Would November the 13th work for you?

**Comment by ThomasChr** [comment]
13.11.2018 -> Should be no problem!

**Comment by niklas-heer** [comment]
Awesome! :+1: 

Just a heads-up maybe Hetzner will host the /dev/night in November, but we are currently figuring that out.
If we can make it work it would be in Gunzenhausen, would that be also okay for you?

**Comment by ThomasChr** [comment]
Gunzenhausen is in fact less km away than Ansbach, so absolutely no problem.
But I hears something about a Presentation Berndwould like to hold at Hetzner... Something about a programming language with two letters.
I don't want to steal his slot!

**Comment by niklas-heer** [comment]
Ah very cool. 
Haha, oh yes I almost forgot. But nonetheless it is enough time for two talks in one night. Even 3 or 4 :smile: 
We have done both already. So no need to worry.

Since the other talks are not completely discussed yet and I don't know if it will work at all in November let's just schedule your talk for November and we'll figure out the rest. :)

Does that work for you?

**Comment by ThomasChr** [comment]
No problem!

**Comment by niklas-heer** [comment]
Awesome, personally I'm siked about the talk :)

**Comment by niklas-heer** [comment]
Hey @ThomasChr so now it is clear. The /dev/night will happen at Hetzner. There will be a talk about a general introduction into Python before your talk so everyone can than follow along even if they are completely new to Python. (hopefully) 
That talk will be held by either Florian or Thomas from Hetzner.

I hope that this is okay for you :)

**Comment by ThomasChr** [comment]
Yep, absolutely!

**Comment by niklas-heer** [comment]
Awesome! Thank you very much! 

I'll update you here when we will announce the event. :smiley:
