### ISSUE TITLE
Codeception

### ISSUE THREAD

**Issue by burned42** [dev-night/talks#36]
* **Speaker**: Bernd Stellwag (burned@zerties.org)
* **Duration**: ~1h + coding challenge
* **Slides**: exist
* **Description**: `Codeception is a testing framework for PHP. It can run different kinds of tests and understands different test formats. The talk should show you what codeception is and why you should use it? It should also cover what codeception can do for you to help you writing tests and the most important part: how do I write different types of tests with it?
I think it would also be cool to have a little hands on challenge after the talk.`

**Comment by burned42** [comment]
@niklas-heer not yet, I will contact you if I can forsee when it would be suitable :)

**Comment by niklas-heer** [comment]
It was great thank you @burned42, I'll close the issue but the talk notes will be here: https://github.com/dev-night/talks/tree/master/slides/2019/034_codeception
