### ISSUE TITLE
Openstreetmap. Bringing the whole world into PostgreSQL

### ISSUE THREAD

**Issue by ThomasChr** [dev-night/talks#37]
* **Speaker**: NEEDED
* **Duration**:
* **Description**: How do we bring the whole world into just three simple data structures (nodes, ways, relations) and silently make the Wikipedia of Maps?

**Comment by niklas-heer** [comment]
Do I understand you correctly that you would like to see a talk about the data structure of Openstreetmap?

(Just making sure I get you talk suggestion)

**Comment by stesie** [comment]
I think that would be an awesome topic :+1:, ... yet I have no clue techwise, just being a less active mapper.

I remember once trying to render customized map tiles, which went wrong miserably though :-)

**Comment by ThomasChr** [comment]
I used the data for the most importand thing you can ever imagine: [Finding the next KFC Fast Food Store](https://www.thomaschristlieb.de/wie-weit-ist-der-naechste-kentucky-fried-chicken-entfernt/)

Yet I'm also not sure if I know enough to make a presentation about the topic, but it's good to know that at least one person would like to see something about it!

**Comment by niklas-heer** [comment]
Awesome so we are on the same page. I'll always find the internals of an application interesting so now we are 3 :+1:

**Comment by niklas-heer** [comment]
Was closed by this PR: https://github.com/dev-night/talks/pull/49
