### ISSUE TITLE
Introduction to Angular

### ISSUE THREAD

**Issue by niklas-heer** [dev-night/talks#4]
* **Speaker**: @ElectricMaxxx 
* **Planned**: 2017-10-10
* **Description**: An introduction into the frontend framework [Angular](https://angular.io/). How to use it and when.

**Comment by ElectricMaxxx** [comment]
das klingt interssant. Hätte da einen beinahe Hands-ON mit dem Titel "Angular von 0 auf 100" im Angebot. Wann wäre denn das Datum?

**Comment by niklas-heer** [comment]
Ah sehr cool :) ja gerne. Die nächste /dev/night ist am 10.10. Würde das passen?

**Comment by ElectricMaxxx** [comment]
passt, nehm ich. Englisch? Zeit-Slot?

**Comment by niklas-heer** [comment]
Prima. :) Englisch wäre prima, da meistens auch englischsprachige Teilnehmer da sind.
Zeit-Slot wie es eben zu deinem Vortrag am besten passt. Du kannst gerne den ganzen Abend haben, da ist es meistens so, dass es dann einen praktischen Teil nach dem Vortrag gibt. Oder wenn die ein ganzer Abend zu viel ist, schauen wir dass wir noch ein Vortrag mit rein nehmen. Das ist immer sehr flexibel :smile:

**Comment by ElectricMaxxx** [comment]
Wann ist ja nicht ganz so wichtig, eher wie lange. Wenn ich ca. 2h hätte wäre das gut, ginge aber auch in einer.

**Comment by niklas-heer** [comment]
Ja das bekommst du auf jeden Fall meistens geht die /dev/night von 19:15 bis ca. 22:00 Uhr je nachdem. Also hättest du locker 2 bis 3 Stunden.

**Comment by niklas-heer** [comment]
@ElectricMaxxx falls das für dich okay ist würde ich schon mal ein Event erstellen auf MeetUp für den 10.10.17 und dich zum Mit-Organisator des Events machen, damit du falls du noch Details hinzufügen willst das machen kann. Falls ja bräuchte ich noch deinen Namen auf meetup.com :)

**Comment by ElectricMaxxx** [comment]
das bin ich: https://www.meetup.com/members/75686242/

**Comment by niklas-heer** [comment]
@ElectricMaxxx ich hab jetzt das Event erstellt. https://www.meetup.com/de-DE/preview/dev_night/events/243492662

Aber du musst noch dem Meetup beitreten, erst dann kann ich dich zum Event Organisator machen. :smile:

**Comment by ElectricMaxxx** [comment]
@niklas-heer können wollen wir heute abend wenn ich was erzählen eine Live-Schalte in Mayflower Barcamp (die sind grad alle in Bayreuth) machen? Könnte mein Screen über appear.in sharen und würde hoffen, dass mein Mikro mitmacht.

**Comment by niklas-heer** [comment]
@ElectricMaxxx klar sollte kein Problem sein. Probieren wir einfach aus :)

**Comment by ElectricMaxxx** [comment]
Btw: i got "mini display port" and VGA output at my PC (!=apple).

**Comment by niklas-heer** [comment]
Should also be no problem. Our laptops also have the same ports :)
