### ISSUE TITLE
Introduction to Service Meshes (Istio)

### ISSUE THREAD

**Issue by stesie** [dev-night/talks#40]
* **Speaker**: @stesie 
* **Duration**: 45m + demo/workshop
* **Slides**: not yet available
* **Description**: Istio is a service mesh, living on Kubernetes. K8s is nice and great, but it lacks some stuff that is kind of a must have in real world production scenarios, ... at least if your microservice fleet integrates over http. First of all it visualizes inter-service traffic (i.e. which service depends on which one), and also allows to control that traffic (like 5% go to this new service version, rest goes to the old one). It also allows to trace a request as it flows through the mesh and has circuit breaking features.
And the good thing: you don't need to modify the services themselfs (i.e. mix those non-functional requirements with your application code), ... instead everything is handled by the infrastructure layer.

**Comment by niklas-heer** [comment]
Thank you @stesie again for the talk. :heart: 

The slides/notes you can find here: https://github.com/dev-night/talks/tree/master/slides/2018/029_service-meshes
