### ISSUE TITLE
Concurrency and other most interesting parts in Go

### ISSUE THREAD

**Issue by narenaryan** [dev-night/talks#42]
* **Speaker**: Naren Yellavula (naren.yellavula@gmail.com)
* **Duration**:  45m
* **Slides**:  https://github.com/narenaryan/concurrent-go
* **Description**: `This talk is a beginner talk for developers, DevOps to understand why simplified concurrency is essential for solving business problems and what Golang can offer in that direction.`

https://golang.org/
https://en.wikipedia.org/wiki/Communicating_sequential_processes

**Comment by niklas-heer** [comment]
https://www.meetup.com/de-DE/dev_night/events/258729595
