### ISSUE TITLE
Self-Contained Systems

### ISSUE THREAD

**Issue by jochenchrist** [dev-night/talks#43]
* **Speaker**: Jochen Christ (jochen.christ@innoq.com)
* **Duration**: 45m
* **Slides**: https://speakerdeck.com/rstrangh/self-contained-systems-1
* **Description**: `The Self-contained System (SCS) approach is an architecture that focuses on a separation of the functionality into many independent systems, making the complete logical system a collaboration of many smaller software systems.`

I could give a talk on Self-contained System.

**Comment by niklas-heer** [comment]
Thank you for your suggestion. That is an interesting topic. 
Maybe that is something for either our special event for the Würzburg Digital festival (2nd April) or Nürnberg Digital festival (16. July). Would you be available on one of the two dates?

**Comment by jochenchrist** [comment]
let’s take 16/07

**Comment by niklas-heer** [comment]
Awesome that is great! Thank you!

Then let's set it as a topic for the 36th /dev/night on 2019-07-16. Now we just need the other lineup. :smile:
