### ISSUE TITLE
Entity vs Behavioral thinking while designing your Python applications

### ISSUE THREAD

**Issue by narenaryan** [dev-night/talks#46]
* **Speaker**: Naren Yellavula (naren.yellavula@gmail)
* **Duration**: e.g. 35-40m (optional)
* **Reference**: e.g. https://medium.com/dev-bits/entity-vs-behavioral-thinking-in-software-design-pythonic-vs-other-philosophies-350dcd09d4e9
* **Description**: `This talk is for beginner and intermediate level Python programmers. It mainly deals with how engineers can model software projects written in Python. Do you consider Entity or Behavior? Let's discuss with real-world examples.`

**Comment by niklas-heer** [comment]
Thank you for the talk! :)

**Comment by narenaryan** [comment]
Thanks to Kasper and @niklas-heer for your support!
