### ISSUE TITLE
Strategies for optimizing your docker builds

### ISSUE THREAD

**Issue by narenaryan** [dev-night/talks#53]
* **Speaker**: Naren Yellavula
* **Duration**:  40m
* **Description**: Are you using Docker for deploying your apps? Then measure the image size and build time. AWS services like ECS, EKS need Docker images and image size affects instance launching time and thereby latencies. In this talk, we discuss how one can optimize a docker image to the maximum level and cut down the build times drastically.

Agenda:
=======

- Choosing the right base image (Slim, Alpine, etc)
- Build time. vs run time dependencies
- Importance of Docker layers
- Multi-stage building
- Using squid proxy for caching the re-installable packages
- Digging deep for junk in images

**Final example**: Deploying a Django application with Wheel(No eggs) and multi-stage builds

Finally `The size matters!`

**Comment by niklas-heer** [comment]
I like the talk idea :+1: 

Do you have a date in mind when you want to give the talk?

**Comment by narenaryan** [comment]
Thanks. Maybe, right after the upcoming talk?

**Comment by niklas-heer** [comment]
Oh sorry didn't see your response. How about the next /dev/night on the 11th of February?

**Comment by narenaryan** [comment]
@niklas-heer Sure. Let us do it on Feb 11th.

**Comment by niklas-heer** [comment]
@narenaryan sure, that's perfect :+1:

**Comment by narenaryan** [comment]
Talk slides: https://docs.google.com/presentation/d/e/2PACX-1vS-c7yQHId-WgrAh5nMtwSJmmcB1angnchDKvhywRHR8aXilRzT3-m3dunU6VgWTT-OrPqmy6kd5-IO/pub?start=false&loop=false&delayms=3000

**Comment by narenaryan** [comment]
Talk code samples:

https://github.com/narenaryan/dev-night-docker-talk
