### ISSUE TITLE
Introduction to Go

### ISSUE THREAD

**Issue by niklas-heer** [dev-night/talks#7]
* **Speaker**:  *NEEDED*
* **Description**: An introduction to the [Go](https://golang.org/) language. How to use it and when. Maybe also some examples where it's used.

**Comment by juancarmo** [comment]
really happy that you guys are closely watching on this topic. Definetly the future for backend ... today

**Comment by niklas-heer** [comment]
Yes definitely we would only need a speaker for this topic, the interest is there :smile:

**Comment by juancarmo** [comment]
One day you will count on me, until then ... live streaming

**Comment by niklas-heer** [comment]
Yes that'll be great. :slightly_smiling_face: 

Yes and our live stream will also get better the next time because we have new Mics :D

**Comment by niklas-heer** [comment]
So maybe in March @juancarmo? :smile:

**Comment by niklas-heer** [comment]
Or @burned42 in November? :smiley:
